language: r
cache: packages

r:
  - devel
warnings_are_errors: false

r_github_packages:
  - jimhester/covr
  - jimhester/lintr

before_install:
  - tlmgr install ly1 mathdesign charter

after_success:
  - Rscript -e 'lintr::lint_package(linters=lintr::with_defaults(line_length_linter = lintr::line_length_linter(120), camel_case_linter = NULL, commented_code_linter = NULL, multiple_dots_linter = NULL, object_usage_linter = NULL, object_length_linter = NULL))'
  - Rscript -e 'covr::codecov()'

addons:
  apt:
    packages:
      - ghostscript
