language: r

dist: trusty

r:
  - devel
warnings_are_errors: false

r_github_packages:
  - jimhester/covr

cache:
  packages: true

before_install:
  - tlmgr install ly1 mathdesign charter

after_success:
  - Rscript -e 'covr::codecov()'

addons:
  apt:
    packages:
      - ghostscript
