language: r
cache: packages

r:
  - devel
warnings_are_errors: false

r_github_packages:
  - jimhester/covr

before_install:
  - tlmgr install ly1 mathdesign charter

after_success:
  - unset CI
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'

addons:
  apt:
    packages:
      - ghostscript
